---

- name: Install the Go-repo.io Repo
  template:
    src: "go-repo.repo.j2"
    dest: "{{ go_repo_repo_file }}"
    owner: root
    group: root
    mode: 0644

- name: Get the GPG Key
  get_url:
    url: "{{ go_repo_repo_gpg_key_url }}"
    dest: "{{ go_repo_repo_gpg_key }}"

- name: Import the Go-repo.io GPG Key
  rpm_key:
    key: "{{ go_repo_repo_gpg_key }}"
    state: present

- name: Delete the On-disk Key
  file:
    path: "{{ go_repo_repo_gpg_key }}"
    state: "absent"
